services:
  efa5:
    image: quay.io/centos/centos:stream9
    privileged: true
    cgroup: host
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - ./eFa5:/eFa5
    ports:
      - "8080:80"
      - "8443:443"
    command: ["/sbin/init"]
